/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as ThreadThreadIdRouteImport } from "./routes/thread.$threadId";
import { Route as ForumForumIdRouteImport } from "./routes/forum.$forumId";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const ThreadThreadIdRoute = ThreadThreadIdRouteImport.update({
  id: "/thread/$threadId",
  path: "/thread/$threadId",
  getParentRoute: () => rootRouteImport,
} as any);
const ForumForumIdRoute = ForumForumIdRouteImport.update({
  id: "/forum/$forumId",
  path: "/forum/$forumId",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/forum/$forumId": typeof ForumForumIdRoute;
  "/thread/$threadId": typeof ThreadThreadIdRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/forum/$forumId": typeof ForumForumIdRoute;
  "/thread/$threadId": typeof ThreadThreadIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/forum/$forumId": typeof ForumForumIdRoute;
  "/thread/$threadId": typeof ThreadThreadIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/forum/$forumId" | "/thread/$threadId";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/forum/$forumId" | "/thread/$threadId";
  id: "__root__" | "/" | "/forum/$forumId" | "/thread/$threadId";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ForumForumIdRoute: typeof ForumForumIdRoute;
  ThreadThreadIdRoute: typeof ThreadThreadIdRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/thread/$threadId": {
      id: "/thread/$threadId";
      path: "/thread/$threadId";
      fullPath: "/thread/$threadId";
      preLoaderRoute: typeof ThreadThreadIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/forum/$forumId": {
      id: "/forum/$forumId";
      path: "/forum/$forumId";
      fullPath: "/forum/$forumId";
      preLoaderRoute: typeof ForumForumIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForumForumIdRoute: ForumForumIdRoute,
  ThreadThreadIdRoute: ThreadThreadIdRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
